### ISSUE TITLE
Latest TYPO3 version 10.4.7 is not installed 

### ISSUE THREAD

**Issue by ghost** [TYPO3/TYPO3.CMS.BaseDistribution#26]
During installation or upgrade the latest TYPO3 version is not fetched for v10 installations that have once been created with the CMS base distributions.

That is because because a Symfony 5 package require `php: ^7.2.4` while https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/master/composer.json#L7 sets PHP platform as `7.2`.

**Comment by t3easy** [comment]
Maybe better set a version of a common PHP Version instead of removing that config. Maybe the same as the core?!

https://github.com/TYPO3/TYPO3.CMS/blob/10.4/composer.json#L29

**Comment by gilbertsoft** [comment]
In the end it turned out that the reason is a [breaking patch of mine](https://review.typo3.org/c/Packages/TYPO3.CMS/+/65405) which we fixed yesterday with https://review.typo3.org/c/Packages/TYPO3.CMS/+/65644. A new release is planed for today so this issue is solved afterwards. So no need to change something here at all.

**Comment by t3easy** [comment]
What's wrong with setting a suitable patch level to get the latest possible packages? Only setting major.minor always leads to problems also with other packages.

**Comment by gilbertsoft** [comment]
Well, it's not wrong but imho not a good starting point for the dist here. Remember the dist should give everyone the opportunity for quick, headaches less start. I personally almost never use patch level version, semver always worked fine for me for the core. This is imho also not a question for a quick start and you always can change the composer.json created by `composer create-project` suitable to your needs afterwards.
As said, the issue here is related to a core bug and the dist worked like this since the beginning and we never had issues with it.

We will introduce more flexible tools in short at get.typo3.org where such options can be implemented to catch more use cases, this also includes the selection of the core packages, including a git or DDEV Local configuration, get some deployment examples (also for TYPO3 Surf where I count on your support @t3easy once I'm starting with this part ;) ). Imho we should stop at this point and join our forces for a new more flexible solution. I hopefully can deploy a first version to the get-dev server after the next t3o sprint next week. Please join the t3o-team-* channels at Slack to get informed about the progress here...

**Comment by jonaseberle** [comment]
This is fixed in TYPO3 v10.4.8
